---
title: "Basic workflow"
description: "Post description"
author: "Florencia D'Andrea"
date: "5/22/2021"
categories:
  - git clone
  - git add
  - git status
  - git commit
  - git pull
  - git push
---

Something that happen when we are teaching a tool is that part of our expertise should be used to confront the students with situations that they have never experienced.

### **Differenciate Between Git and GitHub**

Well done in DSCI 100

This would be key to understand other complicated concepts as the staging area

### **What is a Git repository?**

Time to talk a bit of the filesystem?

Many of the pitfalls the students went through last year were around not understanding the core pieces of vocabulary. For example, some students weren't familiar with basic elements of the file system:

*student: Is a folder the same as a directory?*

This non answered questions leads them to more confusion with upstream terminology that involves a step towards abstraction:

*student: Is a (Git) repository also a synonym of a directory?* *They both look like folders, they should be the same...*

Making the students actively work with these terms is vital to avoid misconceptions to operate over their learning. If these concepts are not clear at this point could create an "snow-ball effect" and evolve to errors more difficult to detect. For example, I have helped to debug errors produced by creating Git repositories inside other Git repositories, mainly because the students were not aware they were doing so.

Link to Stack Overflow question

One question to possible solve that is:

-   Why it is not a good idea to clone the Git repositories you are using for the labs inside the cloned folder of the course?

### **The staging area**

One of the benefits of using the staging area is that you can add more files at the same time.

### **Good commit's names**

### **The connection between Git and GitHub before teaching pull and push**

Here is where the book of Jenny Bryan is pure gold!

Probably the first approach will be start by teaching

one option before getting into all the complexity.

-   One common error arises when, after creating the repository locally

it is not so straightforward to link it to the correspondent

GitHub repository.

### How often commit and how often to pull/push

This is not generally taugh.

### Pulling and pushing are important parts

git push --set-upstream origin new-branch

pushing a new branch
