---
title: "faq"
editor: visual
---

### Why are you doing this? Is there not enough good material out there?

Yes, it is good material! In the section []() I recommend some of my favorites. 
But pay attention that all of that material is for **learning** Git and GitHub, 
not for **teaching** it!

And also if it is a lot of material about education on itself,
I found a hard time finding specific examples on how to teach
the specific didactic. Some of this is far common in other fields.


### How this information could be useful for an educator?

Part of this website's material could be used, for example, to adapt a 
The Carpentries lesson for the specific needs of the course you are teaching. 
Are you using the material to teach undergrad students
with no background on computer sciences? Are you covering different ages? 
Are you training scientist? Are your students struggling with a particular
topic and you would like to reinforce a topic with more activities 
but you don't have time to create new ones? On this cases I think 






I came with this idea as I have been redeveloping DSCI 521 for 
the Master of Data Science Program at the University of British Columbia,
where I am currently working in a postdoc position. Last year I taught this course 
for the first time and listen carefully questions and comments of the 
students about version control.

In particular, version control is something that they will learn in 3 courses:
DSCI 521, DSCI 522 and DSCI 524.

My goal with this website is to condense information that
is potentially good for educators that are brave enough to propose
a new curriculum for the version control lessons or 
redesign/adapt the classes you are using (for example The Carpentries).

for instructors that have to develop a course 


### Can I learn Git and GitHub from this website?

Well, it was not my original purpose. There are many good tutorials and courses
that you can explore for free as for example The Carpentries course. 
Also I recommend Jenny Bryan's book "" and some other tutorials as X and Y.
On the other hand, I couldn't ignore that some of this information  


### That you wrote this book means that you are an amazing instructor?

Lol, no. Being a good instructor has far more than knowing what you should be teaching.
Educators are like wine, they mature with the time and experience.


### What is next?

I will update this website at least 4 times more this year as I will be teaching courses where Git and GitHub are a important tool.
